DROP TABLE IF EXISTS scans;

CREATE TABLE scans (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    targetIp TEXT NOT NULL,
    scanType TEXT NOT NULL,
    alertId TEXT NOT NULL,
    content TEXT NOT NULL
);